### ISSUE TITLE
关于python之基第四个例子**ascii展示对象**

### ISSUE THREAD

**Issue by 0xffm1** [jackzhenguo/python-small-examples#21]
# 问题：python之基第四个例子**ascii展示对象**，在定义Student类后，在第二步直接使用print对新手不友好。

# 建议：把创建实例的步骤补上
` xiaoming = Student('001', 'xiaoming')`

**Comment by 0xffm1** [comment]
问题描述：python之基 第15个例子 执行字符串表示的代码 与 第23个例子执行compile重复。

建议：去重。

**Comment by jackzhenguo** [comment]
感谢提出建议，已经修复，这些例子我会重复打磨，直到最好。

**Comment by jackzhenguo** [comment]
已优化~~
