### ISSUE TITLE
大佬，可以二次分发吗？注明出处和作者。

### ISSUE THREAD

**Issue by fendouai** [jackzhenguo/python-small-examples#27]
二次分发，二次创作，项目licence 是什么？

**Comment by jackzhenguo** [comment]
可以，需要注明出处：https://github.com/jackzhenguo/python-small-examples

**Comment by fendouai** [comment]
感谢大佬授权，已经注明出处：http://examples.tf86.com/。

**Comment by fendouai** [comment]
恭喜，今天上总榜了。
